version = 0.1

# Sample Component Configuration
# Inherits from environment-level configs and adds component-specific settings

[dev.deploy.parameters]
# Component-specific settings for dev (inherits from environments/dev/samconfig.toml)
stack_name = "milaliso-sample-dev"
s3_prefix = "milaliso-sample-dev"
# Inherits: region, capabilities, tags, Environment parameter from env level

[test.deploy.parameters]
# Component-specific settings for test (inherits from environments/test/samconfig.toml)
stack_name = "milaliso-sample-test"
s3_prefix = "milaliso-sample-test"
# Inherits: region, capabilities, tags, Environment parameter from env level

[prod.deploy.parameters]
# Component-specific settings for prod (inherits from environments/prod/samconfig.toml)
stack_name = "milaliso-sample-prod"
s3_prefix = "milaliso-sample-prod"
# Inherits: region, capabilities, tags, Environment parameter from env level