version = 0.1

# Sample Component Configuration

[default.global.parameters]
stack_name = "milaliso-sample"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

[default.deploy.parameters]
s3_bucket = "milaliso-sam-deployments-us-east-1"
s3_prefix = "milaliso-sample"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []

[dev.deploy.parameters]
stack_name = "milaliso-sample-dev"
s3_prefix = "milaliso-sample-dev"
parameter_overrides = "Environment=dev"
tags = "Environment=dev Project=milaliso"

[test.deploy.parameters]
stack_name = "milaliso-sample-test"
s3_prefix = "milaliso-sample-test"
parameter_overrides = "Environment=test"
tags = "Environment=test Project=milaliso"

[prod.deploy.parameters]
stack_name = "milaliso-sample-prod"
s3_prefix = "milaliso-sample-prod"
parameter_overrides = "Environment=prod"
tags = "Environment=prod Project=milaliso"