version = 0.1

# Development Environment - Global Defaults
# These settings are inherited by all components in dev environment

[default.global.parameters]
stack_name_prefix = "milaliso"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
tags = "Environment=dev Project=milaliso"

[default.deploy.parameters]
# Global deployment settings for dev
parameter_overrides = "Environment=dev"

[dev.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
